# Generated by Django 4.0.2 on 2022-02-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=80)),
                ('Village', models.CharField(max_length=80)),
                ('Road', models.CharField(max_length=80)),
                ('Sub_district', models.CharField(max_length=80)),
                ('District', models.CharField(max_length=80)),
                ('Province', models.CharField(max_length=80)),
                ('Code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('IDCardNumber', models.CharField(max_length=20, unique=True)),
                ('Prefix', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=120)),
                ('LastName', models.CharField(max_length=120)),
                ('Gender', models.CharField(max_length=10)),
                ('DateOfBirth', models.DateField()),
                ('Nationality', models.CharField(max_length=20)),
                ('Religion', models.CharField(max_length=20)),
                ('MaritalStatus', models.CharField(max_length=100)),
                ('BloodType', models.CharField(max_length=10)),
                ('AllergyHistory', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=120)),
                ('Department', models.CharField(max_length=120)),
                ('MobilePhone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=120)),
                ('Location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PhrApp.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('IDCardNumber', models.CharField(max_length=20, unique=True)),
                ('Prefix', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=120)),
                ('LastName', models.CharField(max_length=120)),
                ('Gender', models.CharField(max_length=10)),
                ('DateOfBirth', models.DateField()),
                ('Nationality', models.CharField(max_length=20)),
                ('Religion', models.CharField(max_length=20)),
                ('Career', models.CharField(blank=True, max_length=120, null=True)),
                ('CountryOfBirth', models.CharField(max_length=120)),
                ('ProvinceOfBirth', models.CharField(max_length=120)),
                ('MaritalStatus', models.CharField(max_length=100)),
                ('BloodType', models.CharField(max_length=10)),
                ('AllergyHistory', models.CharField(max_length=200)),
                ('FatherName', models.CharField(max_length=120)),
                ('MotherName', models.CharField(max_length=120)),
                ('MobilePhone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=120)),
                ('Location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PhrApp.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('IDCardNumber', models.CharField(max_length=20, unique=True)),
                ('Prefix', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=120)),
                ('LastName', models.CharField(max_length=120)),
                ('Gender', models.CharField(max_length=10)),
                ('DateOfBirth', models.DateField()),
                ('Nationality', models.CharField(max_length=20)),
                ('Religion', models.CharField(max_length=20)),
                ('MaritalStatus', models.CharField(max_length=100)),
                ('BloodType', models.CharField(max_length=10)),
                ('AllergyHistory', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=120)),
                ('ProfessionalLicenseNumber', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=120)),
                ('MobilePhone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=120)),
                ('Location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PhrApp.locations')),
            ],
        ),
    ]
