# Generated by Django 4.0.2 on 2022-02-24 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhrApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialSymptoms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField()),
                ('Symptoms', models.CharField(max_length=150)),
                ('SymptomsDetail', models.CharField(max_length=500)),
                ('Patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhrApp.patients')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhrApp.staffs')),
            ],
        ),
    ]
